/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.io.connect.View;

import icons2.FondoPrincipal;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alsorc
 */
public class Launcher extends javax.swing.JFrame {

     private static FondoPrincipal fondo = new FondoPrincipal();
    
    /**
     * Creates new form Launcher
     */
    public Launcher() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        //this.getContentPane().setBackground(Color.magenta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnMainSonido = new javax.swing.JButton();
        btnMainPresencia = new javax.swing.JButton();
        btnMainLuz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 204, 51));

        jDesktopPane1.setBackground(java.awt.Color.white);
        jDesktopPane1.setBorder(null);
        jDesktopPane1.setEnabled(false);
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(600, 720));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(450, 300));
        jDesktopPane1.setOpaque(false);

        btnMainSonido.setBackground(new java.awt.Color(60, 163, 42));
        btnMainSonido.setForeground(new java.awt.Color(0, 0, 0));
        btnMainSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/btoSonido.png"))); // NOI18N
        btnMainSonido.setToolTipText("Mostrar sensor de sonido");
        btnMainSonido.setBorderPainted(false);
        btnMainSonido.setContentAreaFilled(false);
        btnMainSonido.setMaximumSize(new java.awt.Dimension(132, 48));
        btnMainSonido.setMinimumSize(new java.awt.Dimension(132, 48));
        btnMainSonido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainSonidoActionPerformed(evt);
            }
        });

        btnMainPresencia.setBackground(new java.awt.Color(51, 102, 255));
        btnMainPresencia.setForeground(new java.awt.Color(0, 0, 0));
        btnMainPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/btoMovimiento.png"))); // NOI18N
        btnMainPresencia.setToolTipText("Mostrar sensor de presencia");
        btnMainPresencia.setBorderPainted(false);
        btnMainPresencia.setContentAreaFilled(false);
        btnMainPresencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainPresenciaActionPerformed(evt);
            }
        });

        btnMainLuz.setBackground(new java.awt.Color(248, 255, 123));
        btnMainLuz.setForeground(new java.awt.Color(0, 0, 0));
        btnMainLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/btoLuz.png"))); // NOI18N
        btnMainLuz.setToolTipText("Mostrar sensor de luz");
        btnMainLuz.setBorderPainted(false);
        btnMainLuz.setContentAreaFilled(false);
        btnMainLuz.setMaximumSize(new java.awt.Dimension(132, 48));
        btnMainLuz.setMinimumSize(new java.awt.Dimension(132, 48));
        btnMainLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainLuzActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Droid Sans Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 0, 196));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/bienvenido.png"))); // NOI18N

        jDesktopPane1.setLayer(btnMainSonido, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnMainPresencia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnMainLuz, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnMainSonido, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMainPresencia, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnMainLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnMainLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMainPresencia)
                    .addComponent(btnMainSonido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainLuzActionPerformed
         try {
             LightView lv = new LightView();
             jDesktopPane1.add(lv);
             lv.setVisible(true);
         } catch (IOException ex) {
             Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnMainLuzActionPerformed

    private void btnMainPresenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainPresenciaActionPerformed
         try {
             PresenceView pv = new PresenceView();
             jDesktopPane1.add(pv);
             pv.setVisible(true);
         } catch (IOException ex) {
             Logger.getLogger(Launcher.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnMainPresenciaActionPerformed

    private void btnMainSonidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainSonidoActionPerformed
        SoundView sv = new SoundView();

        jDesktopPane1.add(sv);
        sv.setVisible(true);
    }//GEN-LAST:event_btnMainSonidoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Launcher(){}.setVisible(true);
                System.out.println("INICIANDO");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMainLuz;
    private javax.swing.JButton btnMainPresencia;
    private javax.swing.JButton btnMainSonido;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
