/*
 * To change this license header, choose License Headers in Project Properties. * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.io.connect.View;

import com.io.connect.Messages;

import com.io.connect.SocketConectorView;
import icons2.FondoLuz;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author alsorc
 */
public class LightView extends javax.swing.JInternalFrame{

    private static FondoLuz fondo = new FondoLuz();
    SocketConectorView mySocket;
    /**
     * Creates new form LightView
     */
    public LightView() throws IOException {
        this.mySocket = SocketConectorView.getSocketConector();
        this.setContentPane(fondo);
        initComponents();
        JLabel iconoFoco = this.iconFoco;
        loadStates(); 

        Thread task = new Thread() {
            @Override
            public void run() {
                String msgBackFromSensor;
                System.out.println("******LOG LIGH TVIEW********");
                while (true) {
                    
                    try {
                        msgBackFromSensor = mySocket.getInputData().readUTF();
                        
                        if(msgBackFromSensor != null|| msgBackFromSensor.equals("")){
                            System.out.println(msgBackFromSensor);
                        }
                        
                        System.out.println("response: " + msgBackFromSensor);
                        switch (msgBackFromSensor) {
                            case "LIGHT_SENSOR_ON":
                                System.out.println("ENCENDIDO");
                                btnApagarLuz.setEnabled(true);
                                iconoFoco.setEnabled(true);
                                break;
                            case "LIGHT_SENSOR_OFF":
                                System.out.println("APAGADO");
                                iconoFoco.setEnabled(false);
                                btnApagarLuz.setEnabled(false);
                                break;
                            default:
                                System.err.println("Escuchando");                                
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(LightView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        task.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEncenderLuz = new javax.swing.JButton();
        btnApagarLuz = new javax.swing.JButton();
        iconFoco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setBackground(new java.awt.Color(170, 219, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/luz.png"))); // NOI18N

        btnEncenderLuz.setBackground(new java.awt.Color(170, 219, 255));
        btnEncenderLuz.setForeground(new java.awt.Color(0, 204, 0));
        btnEncenderLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/on.png"))); // NOI18N
        btnEncenderLuz.setBorderPainted(false);
        btnEncenderLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderLuzActionPerformed(evt);
            }
        });

        btnApagarLuz.setBackground(new java.awt.Color(170, 219, 255));
        btnApagarLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/off.png"))); // NOI18N
        btnApagarLuz.setBorderPainted(false);
        btnApagarLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarLuzActionPerformed(evt);
            }
        });

        iconFoco.setBackground(new java.awt.Color(170, 219, 255));
        iconFoco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/light128.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(170, 219, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/Encender.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(170, 219, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/Apagar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnApagarLuz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEncenderLuz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconFoco)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEncenderLuz)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagarLuz))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iconFoco, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarLuzActionPerformed
        try {
          mySocket.sendMessage(Messages.LIGHT_OFF);
        } catch (IOException ex) {
            Logger.getLogger(LightView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApagarLuzActionPerformed

    private void btnEncenderLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderLuzActionPerformed
        try {
            mySocket.sendMessage(Messages.LIGHT_ON);
        } catch (IOException ex) {
            Logger.getLogger(LightView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEncenderLuzActionPerformed

    public void loadStates() {
        this.iconFoco.setEnabled(false);
        this.btnApagarLuz.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarLuz;
    private javax.swing.JButton btnEncenderLuz;
    private javax.swing.JLabel iconFoco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

     
    
}
