/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.io.connect.View;

import com.io.connect.Messages;
import com.io.connect.SocketConectorView;
import icons2.FondoMovimiento;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author alsorc
 */
public class PresenceView extends javax.swing.JInternalFrame {

    private static FondoMovimiento fondo = new FondoMovimiento();
    SocketConectorView mySocket;
    /**
     * Creates new form LightView
     */
    public PresenceView() throws IOException {
        this.mySocket = new SocketConectorView();
        this.setContentPane(fondo);
        initComponents();
        JLabel iconito = this.iconAlertPresencia;
        loadStates();
        Thread task = new Thread() {
            @Override
            public void run() {
                String msgBackFromSensor;
                System.out.println("******LOG LIGH TVIEW********");
                while (true) {

                    try {
                        msgBackFromSensor = mySocket.getInputData().readUTF();
                        System.out.println("response: " + msgBackFromSensor);
                        switch (msgBackFromSensor) {
                            case "DESKTOP_PRESENCE_ON":
                                System.out.println("ENCENDIDO");
                                btnApagarPresencia.setEnabled(true);
                                btnAnalizarPresencia.setEnabled(true);
                                break;
                            case "DESKTOP_PRESENCE_OFF":
                                System.out.println("APAGADO");
                                iconito.setEnabled(false);
                                btnApagarPresencia.setEnabled(false);
                                break;
                            case "DESKTOP_PRESENCE_1":
                                System.out.println("PRESENCE!");
                                iconito.setEnabled(true);
                                break;
                            case "DESKTOP_PRESENCE_0":
                                System.out.println("NO PRESENCE");
                                iconito.setEnabled(false);
                                break;
                            case "DESKTOP_PRESENCE_2":
                                System.out.println("NO PRESENCE");
                                iconito.setEnabled(false);
                                break;
                            default:
                                System.err.println("LISTENING");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(PresenceView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        task.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEncenderPresencia = new javax.swing.JButton();
        btnApagarPresencia = new javax.swing.JButton();
        btnAnalizarPresencia = new javax.swing.JButton();
        iconAlertPresencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setBackground(new java.awt.Color(254, 216, 229));
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/movimiento.png"))); // NOI18N

        btnEncenderPresencia.setBackground(new java.awt.Color(254, 216, 229));
        btnEncenderPresencia.setForeground(new java.awt.Color(76, 14, 36));
        btnEncenderPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/on.png"))); // NOI18N
        btnEncenderPresencia.setBorderPainted(false);
        btnEncenderPresencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderPresenciaActionPerformed(evt);
            }
        });

        btnApagarPresencia.setBackground(new java.awt.Color(254, 216, 229));
        btnApagarPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/off.png"))); // NOI18N
        btnApagarPresencia.setBorderPainted(false);
        btnApagarPresencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarPresenciaActionPerformed(evt);
            }
        });

        btnAnalizarPresencia.setBackground(new java.awt.Color(254, 216, 229));
        btnAnalizarPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/analizar.png"))); // NOI18N
        btnAnalizarPresencia.setBorderPainted(false);
        btnAnalizarPresencia.setContentAreaFilled(false);
        btnAnalizarPresencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarPresenciaActionPerformed(evt);
            }
        });

        iconAlertPresencia.setBackground(new java.awt.Color(254, 216, 229));
        iconAlertPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alert128.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(254, 216, 229));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/Encender.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(254, 216, 229));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/Apagar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnalizarPresencia, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApagarPresencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEncenderPresencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(iconAlertPresencia)
                        .addGap(41, 41, 41))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnApagarPresencia, btnEncenderPresencia});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEncenderPresencia)
                        .addGap(18, 18, 18)
                        .addComponent(btnApagarPresencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconAlertPresencia)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnAnalizarPresencia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnApagarPresencia, btnEncenderPresencia});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarPresenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarPresenciaActionPerformed
        try {
            mySocket.sendMessage(Messages.PRESENCE_OFF);
        } catch (IOException ex) {
            Logger.getLogger(PresenceView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApagarPresenciaActionPerformed

    private void btnEncenderPresenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderPresenciaActionPerformed
        try {
            mySocket.sendMessage(Messages.PRESENCE_ON);
        } catch (IOException ex) {
            Logger.getLogger(PresenceView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEncenderPresenciaActionPerformed

    private void btnAnalizarPresenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarPresenciaActionPerformed
        try {
            SocketConectorView.getSocketConector().sendMessage(Messages.PRESENCE_ANALIZAR);
        } catch (IOException ex) {
            Logger.getLogger(PresenceView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarPresenciaActionPerformed

    public void loadStates() {
        this.iconAlertPresencia.setEnabled(false);
        this.btnAnalizarPresencia.setEnabled(false);
        this.btnApagarPresencia.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizarPresencia;
    private javax.swing.JButton btnApagarPresencia;
    private javax.swing.JButton btnEncenderPresencia;
    private javax.swing.JLabel iconAlertPresencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
