/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.io.connect.View;

import com.io.connect.Messages;
import com.io.connect.SocketConectorView;
import icons2.FondoSonido;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author alsorc
 */
public class SoundView extends javax.swing.JInternalFrame {

    private static FondoSonido fondo = new FondoSonido();
    SocketConectorView mySocket;

    /**
     * Creates new form LightView
     */
    public SoundView() throws IOException {
        this.setContentPane(fondo);
        initComponents();
        this.mySocket = new SocketConectorView();
        JLabel iconito = this.iconAlert;
        loadStates();
        Thread task = new Thread() {
            @Override
            public void run() {
                String msgBackFromSensor;
                System.out.println("******LOG SOUND TVIEW********");
                while (true) {

                    try {
                        msgBackFromSensor = mySocket.getInputData().readUTF();
                         if(msgBackFromSensor != null|| msgBackFromSensor.equals("")){
                            System.out.println(msgBackFromSensor);
                        }
                        System.out.println("response: " + msgBackFromSensor);
                        switch (msgBackFromSensor) {
                            case "DESKTOP_SOUND_ON":
                                System.out.println("ENCENDIDO");
                                btnApagar.setEnabled(true);
                                btnAnalizar.setEnabled(true);
                                break;
                            case "DESKTOP_SOUND_OFF":
                                System.out.println("APAGADO");
                                iconito.setEnabled(false);
                                btnApagar.setEnabled(false);
                                break;
                            case "DESKTOP_SOUND_1":
                                System.out.println("SOUND!");
                                iconito.setEnabled(true);
                                break;
                            case "DESKTOP_SOUND_0":
                                System.out.println("NO SOUND");
                                iconito.setEnabled(false);
                                break;
                            case "DESKTOP_SOUND_2":
                                System.out.println("NO SOUND");
                                iconito.setEnabled(false);
                                break;
                            default:
                                System.err.println("LISTENING...");
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(SoundView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        task.start();

    }

    public void loadStates() {
        this.iconAlert.setEnabled(false);
        this.btnAnalizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        iconAlert = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setBackground(new java.awt.Color(195, 242, 198));
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/sonido.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(160, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(160, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 90));

        btnEncender.setBackground(new java.awt.Color(195, 242, 198));
        btnEncender.setForeground(new java.awt.Color(195, 242, 198));
        btnEncender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/on.png"))); // NOI18N
        btnEncender.setBorderPainted(false);
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(195, 242, 198));
        btnApagar.setForeground(new java.awt.Color(195, 242, 198));
        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/off.png"))); // NOI18N
        btnApagar.setBorderPainted(false);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnAnalizar.setBackground(new java.awt.Color(195, 242, 198));
        btnAnalizar.setForeground(new java.awt.Color(195, 242, 198));
        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/analizar.png"))); // NOI18N
        btnAnalizar.setBorderPainted(false);
        btnAnalizar.setContentAreaFilled(false);
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        iconAlert.setBackground(new java.awt.Color(195, 242, 198));
        iconAlert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alert128.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(195, 242, 198));
        jLabel3.setForeground(new java.awt.Color(195, 242, 198));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/Encender.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(195, 242, 198));
        jLabel4.setForeground(new java.awt.Color(195, 242, 198));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/Apagar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAnalizar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEncender)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnApagar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))))
                                .addGap(18, 18, 18)
                                .addComponent(iconAlert))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnAnalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEncender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconAlert)
                        .addGap(133, 133, 133)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        try {
            mySocket.sendMessage(Messages.SOUND_OFF);
        } catch (IOException ex) {
            Logger.getLogger(SoundView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed

        try {
            mySocket.sendMessage(Messages.SOUND_ON);
        } catch (IOException ex) {
            Logger.getLogger(SoundView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        try {
            mySocket.sendMessage(Messages.SOUND_ANALIZAR);
        } catch (IOException ex) {
            Logger.getLogger(SoundView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAnalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEncender;
    private javax.swing.JLabel iconAlert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
