/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.io.connect.View;

import com.io.connect.Cliente;
import com.io.connect.Servidor;
import icons2.FondoPanel;
import java.util.Observable;
import java.util.Observer;
/**
 *
 * @author alsorc
 */
public class SoundView extends javax.swing.JInternalFrame implements Observer{
    
    private final String iPSensorSonido = "25.36.68.101";
    
    private static Servidor myServer;
    
    FondoPanel fondo =  new FondoPanel();
    /**
     * Creates new form LightView
     */
    public SoundView() {
        this.setContentPane(fondo);
        initComponents();
        loadStates();
        Servidor s = getServidor();
        s.addObserver(this);
        Thread t = new Thread(s);
        t.start();
    }
    
    public static Servidor getServidor(){
        if(myServer == null)
            myServer = new Servidor(5000);
        return myServer;
    }
    

    public void loadStates(){
        this.iconPresencia.setEnabled(false);
        this.iconAlert.setEnabled(false);
        this.btnAnalizar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEncender = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        iconPresencia = new javax.swing.JLabel();
        btnAnalizar = new javax.swing.JButton();
        iconAlert = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/sonido.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(160, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(160, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 90));

        btnEncender.setBackground(java.awt.Color.blue);
        btnEncender.setForeground(new java.awt.Color(0, 204, 0));
        btnEncender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/on.png"))); // NOI18N
        btnEncender.setBorderPainted(false);
        btnEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderActionPerformed(evt);
            }
        });

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/off.png"))); // NOI18N
        btnApagar.setBorderPainted(false);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        iconPresencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPresencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sound128.png"))); // NOI18N

        btnAnalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons2/analizar.png"))); // NOI18N
        btnAnalizar.setBorderPainted(false);
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        iconAlert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alert128.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 217, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(iconAlert)
                    .addComponent(btnAnalizar)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(223, 223, 223))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApagar)
                    .addComponent(btnEncender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconPresencia)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApagar)
                        .addGap(112, 112, 112))
                    .addComponent(iconAlert, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addComponent(btnAnalizar)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(iconPresencia)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        this.iconPresencia.setEnabled(false);
        this.iconAlert.setEnabled(false);
        this.btnAnalizar.setEnabled(false);
        
        
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderActionPerformed
        this.iconPresencia.setEnabled(true);
        this.btnAnalizar.setEnabled(true);
    }//GEN-LAST:event_btnEncenderActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        String mensaje = "ANALIZAR";
        System.out.println("----Conectando a cliente---");
        Cliente c = new Cliente( 5000, mensaje.toUpperCase(), iPSensorSonido);
        Thread t = new Thread(c);
        t.start();
    }//GEN-LAST:event_btnAnalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEncender;
    private javax.swing.JLabel iconAlert;
    private javax.swing.JLabel iconPresencia;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        System.out.println((String)o1);
        switch((String)o1){
            case "ALERT":
                this.iconAlert.setEnabled(true);
                System.out.println("SONIDO DETECTADO");
                break;
            case "CALM":
                  this.iconAlert.setEnabled(false);
                  System.out.println("NO PRESENCIA");
                  break;
            default:
                System.err.println("Respuesta no válida " + (String)o1);
        }
    
    }
 
}